selected_scheme scheme-basic
collection-bibtexextra 1
collection-fontsrecommended 1
collection-pictures 1
collection-langenglish 1
collection-langcjk 1
collection-langjapanese 1
collection-mathscience 1
option_doc 0
option_src 0
